// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcsjmukcehybhyuxehes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjc2ptdWtjZWh5Ymh5dXhlaGVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4Mjk5NTYsImV4cCI6MjA3MDQwNTk1Nn0.2bCqAexubr7q6VJyMcD6MZvcPbAij3iHn34pcUp0xGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});